version: '3'
services:
  hadoop:
    image: aquelatecnologia/hadoop:2.9.1 
    volumes:
      - ./volume:/volume 
    container_name: hadoop
    hostname: hadoop
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./database/:/var/lib/mysql/
    ports:
      - 3306:3306
    container_name: mysql
    hostname: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    container_name: phpmyadmin
    hostname: phpmyadmin